### ISSUE TITLE
Conan build error on Windows 10 - possible gluegen error?

### ISSUE THREAD

**Issue by pirosm1** [inexorgame/inexor-core#457] opened 2017-07-25 08:42 UTC
Hi all,

Encountered some build errors when running tool/create_bat_visual_studio2017_project.bat.
Specifically, encountered 2 warnings and 1 error.

Here's my environment:
branch: master
git log -1 output: commit 2078d8b7e44a3100f80827add58f965f614f3bf0 (HEAD -> master, tag: 0.8.10-alpha, origin/master, origin/HEAD)
platform: Windows 10
IDE: Visual Studio 15 2017
CMake -v: 3.9.0
Conan: 0.25.1

Here's a file with all the output:  [create_visual_studio2017_project_OUTPUT.txt](https://github.com/inexorgame/inexor-core/files/1172397/create_visual_studio2017_project_OUTPUT.txt)

The error occurs around line 517-518.

Since the Inexor.sln still gens, I decided to move along with the wiki and try to build INSTALL. I was met with two errors: 
![errors](https://user-images.githubusercontent.com/14130170/28562896-e3802e36-70d8-11e7-82c0-56b063292082.PNG)

The second one looks like a cmake command, so I ran that and got:
> CMake Error at inexor/client/cmake_install.cmake:31 (file):
file INSTALL cannot find
  "C:/Users/mneme_000/inexor-core/build/inexor/rpc/inexor/RPCTreeData.gen.proto".
Call Stack (most recent call first):
  inexor/cmake_install.cmake:38 (include)
  cmake_install.cmake:36 (include)

Looking into inexor-core/build/inexor/rpc/inexor/RPCTreeData.gen.proto I see only one gen'd file: doxygen-parser.conf

Thanks go to @Fohlen for helping me in Riot!
He suggested that I regenerate gluegen, but I'm not sure how to proceed with that process.

**Comment by a-teammate** [comment] 2017-07-25 15:50
I found the root of the error:
Doxygen is covered by our package manager conan.
conan is able to cache packages in prebuilt form and a left over absolute path from the prebuilding on appveyor caused that everytime one tries to execute doxygen it uses that left-over path.

as a workaround you could add `--build doxygen` in the create_visual_studio_project.bat of your choice :D

**Comment by pirosm1** [comment] 2017-07-25 16:09
Awesome! I won't be able to try this out to later. But until then 🤞

**Comment by pirosm1** [comment] 2017-07-26 03:46
Additional workaround from @Croydon which manually builds the doxygen dependency:

`conan install doxygen/1.8.13@inexorgame/stable --build -s compiler="Visual Studio" -s compiler.version=15 -s compiler.runtime=MTd -s build_type=Debug`

then run the create_visual_studio_project.bat of choice once more

**Comment by Fohlen** [comment] 2017-07-26 11:20
Can you guys note that down as "known pitfall" in the wiki and close this issue?

**Comment by a-teammate** [comment] 2017-07-26 12:14
no, since this issue needs a fix.
we really should make a "Definition of Done" for issues at the hackathon.

**Comment by Croydon** [comment] 2017-07-26 13:34
We "just" need to rebuild the Conan packages, right? Your commit fixed the cause?

**Comment by a-teammate** [comment] 2017-07-26 23:57
yes, exactly! :)
and i didnt upload the recipe to jfrog either

**Comment by Croydon** [comment] 2017-07-27 01:58
I did upload it right after I did ask you if you have done it already. Packages building is another topic, since someone™ did merge a not-ready pr a while ago and it is still broken :P

**Comment by pirosm1** [comment] 2017-07-27 06:02
Blew away my local repo, and re-built on the same platform. Success!... mostly. I think this bug is resolved though. 👍 for close

**Closed** 2017-07-27 10:20 UTC
Labels: cat:BUG, org:in progress, prio:BUILD FAILING
