### ISSUE TITLE
Inexor repo media initializing should be done in a dedicated process = better error handling

### ISSUE THREAD

**Issue by Fohlen** [inexorgame/inexor-core#434] opened 2017-06-20 17:58 UTC
Right now when a media repository is not properly initialized the whole thing will blow up with:
```
Jun 20 19:52:04 @inexor-game/flex/server[28817] INFO:  Cannot read property 'substr' of undefined
  err: TypeError: Cannot read property 'substr' of undefined
      at GitRepositoryManager.mergeBranches (./node_modules/@inexor-game/media/Repository.js:513:29)
      at ./node_modules/@inexor-game/media/Repository.js:459:23
      at tryCallOne (./node_modules/nodegit-promise/lib/core.js:37:12)
      at ./node_modules/nodegit-promise/lib/core.js:103:15
      at flush (./node_modules/asap/raw.js:50:29)
      at _combinedTickCallback (internal/process/next_tick.js:73:7)
      at process._tickCallback (internal/process/next_tick.js:104:9)
```

It would be good to also spawn the git cloning in a dedicated process, so it will not be killed when flex is killed.

**Comment by a-teammate** [comment] 2017-06-21 07:22
duplicate of #406?

**Comment by aschaeffer** [comment] 2017-06-21 08:15
At least very similar. I know we need more work to get the media repository fetch and update mechanism bullet proof. Please continue discussion with #406 .

**Closed by aschaeffer** 2017-06-21 08:15 UTC
Labels: cat:BUG, diff:beginner
